config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :new, :create, :show, :edit, :update]

  root to: redirect('users')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_reader :password
  
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: { message: "Password can't be blank." }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, presence: true, uniqueness: true
  
  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return user if !user.nil? && user.is_password?(password)
    nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :login!
  helper_method :logged_in?

  private

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !current_user.nil?
  end

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_no_user!
    redirect_to '#' if current_user
  end

  def require_user!
    redirect_to '#' if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username], 
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Incorrect username and/or password."]
      render :new
    else
      login!(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if @user
    else
      redirect_to users_url
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Working</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="main-nav">
      <h1><%= link_to 'Working', users_url %></h1>
      <div>
        <% if current_user.nil? %>
          <%= link_to 'Sign Up', new_user_url %>
          <%= link_to 'Sign In', new_session_url %>
        <% else %>
          <%= current_user.username %>
          <form action="<%= session_url %>" method="POST">
            <input type="hidden" name="_method" value="DELETE">
            <%= auth_token %>
            <input type="submit" value="Sign Out">
          </form>
        <% end %>
      </div>
    </nav>
    <main>
      <% flash.each do |key, value| %>
        <div class="flash"><%= value %></div> 
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <h6>We are a work in progress.</h6>    
    </footer>
  </body>
</html>

app/views/users/_form.html.erb
<% if action == :edit %>
  <% action_url = user_url(user) %>
<% else %>
  <% action_url = users_url %>
<% end %>

<form action="<%= action_url %>" method="POST">
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <%= auth_token %>

  <label for="user_username">Username:</label>
  <input type="text" id="user_username" name="user[username]" value="<%= @user.username %>">
  <br><br>

  <label for="user_email">Email:</label>
  <input type="email" id="user_email" name="user[email]" value="<%= @user.email %>">
  <br><br>

  <label for="user_password">Password:</label>
  <input type="password" id="user_password" name="user[password]" value="<%= @user.password %>">
  <br><br>

  <input type="submit" value="<%= (action == :edit) ? 'Edit' : 'Submit' %>">
</form>

<h2><%= link_to 'List of Workers', users_url %></h2>

app/views/users/edit.html.erb
<h1>Edit Worker</h1>

<%= render 'form', action: :edit, user: @user %>

app/views/users/index.html.erb
<h1>Workers</h1>

<% @users.each do |user| %>
  <ul>
    <li>
      <%= link_to user.username, user_url(user) %>
    </li>
  </ul>
<% end %>

app/views/users/new.html.erb
<h1>Create Worker</h1>

<%= render 'form', action: :new, user: @user %>

app/views/users/show.html.erb
<h1><%= link_to @user.username, edit_user_url %></h1>

<p>Welcome, <%= @user.username %>!</p>

<h2><%= link_to 'List of Workers', users_url %></h2>